### ISSUE TITLE
flutter_flipperkit 一直安装不上

### ISSUE THREAD

**Issue by flutterbest** [blankapp/flutter_flipperkit#13]
```
    -> Using sqflite (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/OpenSSL-Static/lib-ios/libcrypto.a, and /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/OpenSSL-Static/lib-ios/libssl.a)

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:81:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
        [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        [0m

Error running pod install
Error launching application on iPhone X.
```

**Comment by lijy91** [comment]
@niugengyun 还在调查，暂时未找到解决方法

**Comment by tinyc-z** [comment]
echo "export LANG=en_US.UTF-8" >> ~/.profile

**Comment by RoJoHub** [comment]
The Solution:

https://github.com/react-native-community/react-native-maps/issues/1923#issuecomment-373625709


```
pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

**Comment by flutterbest** [comment]
> The Solution:
> 
> [react-native-community/react-native-maps#1923 (comment)](https://github.com/react-native-community/react-native-maps/issues/1923#issuecomment-373625709)
> 
> ```
> pre_install do |installer|
> 	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
> 	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> ```

不行的 还是报错的

**Comment by flutterbest** [comment]
> echo "export LANG=en_US.UTF-8" >> ~/.profile

配置过的 还是不行

**Comment by tinyc-z** [comment]
更新下cocoapods版本吧，你这个太老了

**Comment by flutterbest** [comment]
> 更新下cocoapods版本吧，你这个太老了

好的 我先升级到最新版

**Comment by flutterbest** [comment]
> 更新下cocoapods版本吧，你这个太老了

还是不行 我的配置：

```
➜  ~ pod --version
1.7.2
➜  ~ cat ~/.profile
export LANG=en_US.UTF-8
➜  ~
```




```
    -> Installing sqflite (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/OpenSSL-Static/lib-ios/libcrypto.a, and /Users/niugengyun/AndroidStudioProjects/shenghuopai/ios/Pods/OpenSSL-Static/lib-ios/libssl.a)

    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:81:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:71:in `each_key'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:71:in `block in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
        [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        [0m

Error running pod install
Error launching application on iPhone X.
```

**Comment by lijy91** [comment]
@niugengyun 解决方法：https://github.com/blankapp/flutter_flipperkit/issues/10#issuecomment-505138362


请参考示例：
### [https://github.com/blankapp/flutter_flipperkit_examples/tree/master/flutter_inappbrowser_example](https://github.com/blankapp/flutter_flipperkit_examples/tree/master/flutter_inappbrowser_example)
