### ISSUE TITLE
Not able to Build iOS default flutter app

### ISSUE THREAD

**Issue by paulVulog** [blankapp/flutter_flipperkit#34]
Hi, I am not able to build an iOS app using your plugin and the default flutter app.

Here is my configuration : 

### Flutter Doctor : 

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
```

### Flutter dependencies :  pubspec.yaml

```
name: temp_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #https://pub.dev/packages/flutter_flipperkit
  flutter_flipperkit: ^0.0.24

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
```

### iOS pod file : 

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_flipperkit/flutter_flipperkit.dart';

void main() {

  WidgetsFlutterBinding.ensureInitialized();

  //setup Flipper
  FlipperClient flipperClient = FlipperClient.getDefault();
  flipperClient.addPlugin(new FlipperNetworkPlugin());
  flipperClient.addPlugin(new FlipperSharedPreferencesPlugin());
  flipperClient.start();

  runApp(MyApp());
}

...

```

---

Everything is fine with Android Builds, but iOS is not working by default using the basic flutter sample app.
But, I am able to bypass the issue for iOS.

Only if I remove those two values from the pod file, everything is fine.
  use_frameworks!
  use_modular_headers!

However, I would like to keep those values because my current project need them.
Is there a fix waiting on that side to be able to build the iOS app with the default pod file configuration ?

Thanks. 

---

### Additional logs : 

Error if I build with ' use_frameworks! ' : 

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - flutter_flipperkit

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_flipperkit` from `.symlinks/plugins/flutter_flipperkit/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_3_2_5.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.72.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_e_7.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/e/7/ComponentKit/0.30/ComponentKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_3_d_9.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/d/9/RenderCore/0.30/RenderCore.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_a_e_a.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/e/a/Flipper/0.73.0/Flipper.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/e/a/Flipper/0.61.0/Flipper.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_5_7_2.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/5/7/2/Flipper-Folly/2.3.0/Flipper-Folly.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_d_1_3.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/d/1/3/Flipper-RSocket/1.1.0/Flipper-RSocket.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/d/1/3/Flipper-RSocket/1.1.0/Flipper-RSocket.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/d/9/RenderCore/0.30/RenderCore.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/2/5/FlipperKit/0.61.0/FlipperKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_4.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/d/4/CocoaAsyncSocket/7.6.5/CocoaAsyncSocket.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_d_6_6.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/d/6/6/Flipper-PeerTalk/0.0.4/Flipper-PeerTalk.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/f/e/7/ComponentKit/0.30/ComponentKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_b_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/8/b/e/Yoga/1.14.0/Yoga.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/d/9/RenderCore/0.30/RenderCore.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_9_4_7.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/4/7/YogaKit/1.18.1/YogaKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/d/6/6/Flipper-PeerTalk/0.0.4/Flipper-PeerTalk.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/5/7/2/Flipper-Folly/2.3.0/Flipper-Folly.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_7_d.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_2_7_2.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/2/7/2/Flipper-Glog/0.3.6/Flipper-Glog.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_3_3_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/3/c/Flipper-DoubleConversion/1.1.7/Flipper-DoubleConversion.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_d_6.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/d/6/OpenSSL-Universal/1.1.180/OpenSSL-Universal.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_a_a_0.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/a/0/CocoaLibEvent/1.0.0/CocoaLibEvent.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/a/a/0/CocoaLibEvent/1.0.0/CocoaLibEvent.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/4/7/YogaKit/1.18.1/YogaKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/d/4/CocoaAsyncSocket/7.6.5/CocoaAsyncSocket.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/2/7/2/Flipper-Glog/0.3.6/Flipper-Glog.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/3/3/c/Flipper-DoubleConversion/1.1.7/Flipper-DoubleConversion.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/d/6/OpenSSL-Universal/1.0.2.20/OpenSSL-Universal.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/d/6/OpenSSL-Universal/1.0.2.20/OpenSSL-Universal.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/8/b/e/Yoga/1.14.0/Yoga.podspec.json exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      - CocoaAsyncSocket
      - CocoaLibEvent
      - ComponentKit
      - Flipper
      - Flipper-DoubleConversion
      - Flipper-Folly
      - Flipper-Glog
      - Flipper-PeerTalk
      - Flipper-RSocket
      - FlipperKit
      - Flutter
      - OpenSSL-Universal
      - RenderCore
      - Yoga
      - YogaKit
      - boost-for-react-native
      - flutter_flipperkit

    Downloading dependencies

    -> Using CocoaAsyncSocket (7.6.5)

    -> Using CocoaLibEvent (1.0.0)

    -> Using ComponentKit (0.30)

    -> Using Flipper (0.61.0)

    -> Using Flipper-DoubleConversion (1.1.7)

    -> Using Flipper-Folly (2.3.0)

    -> Using Flipper-Glog (0.3.6)

    -> Using Flipper-PeerTalk (0.0.4)

    -> Using Flipper-RSocket (1.1.0)

    -> Using FlipperKit (0.61.0)

    -> Using Flutter (1.0.0)

    -> Using OpenSSL-Universal (1.0.2.20)

    -> Using RenderCore (0.30)

    -> Using Yoga (1.14.0)

    -> Using YogaKit (1.18.1)

    -> Using boost-for-react-native (1.63.0)

    -> Using flutter_flipperkit (0.0.24)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/user_name/Documents/dev/perso/temp_app/ios/Pods/CocoaLibEvent/lib/libevent.a, /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/CocoaLibEvent/lib/libevent_core.a, /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/CocoaLibEvent/lib/libevent_extra.a, /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/CocoaLibEvent/lib/libevent_pthreads.a, /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a, and /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/OpenSSL-Universal/ios/lib/libssl.a)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:595:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12 Pro Max.
```

error if I built with ' use_modular_headers! ' : 

A 10 000+ lines of error finishing by : 
```

    1 error generated.
    While building module 'flutter_flipperkit' imported from /Users/user_name/Documents/dev/perso/temp_app/ios/Runner/GeneratedPluginRegistrant.m:8:
    While building module 'FlipperKit' imported from /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/flutter_flipperkit/FlipperDatabaseBrowserPlugin.h:2:
    In file included from <module-includes>:1:
    In file included from /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/FlipperKit/FlipperKit-umbrella.h:13:
    In file included from /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/FlipperKit/FlipperClient.h:11:
    /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/FlipperKit/FlipperKitCertificateProvider.h:10:9: fatal error: could not build module 'Flipper'
    #import <Flipper/FlipperCertificateExchangeMedium.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'flutter_flipperkit' imported from /Users/user_name/Documents/dev/perso/temp_app/ios/Runner/GeneratedPluginRegistrant.m:8:
    In file included from <module-includes>:1:
    In file included from /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/flutter_flipperkit/flutter_flipperkit-umbrella.h:14:
    /Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Headers/Public/flutter_flipperkit/FlipperDatabaseBrowserPlugin.h:2:9: fatal error: could not build module 'FlipperKit'
    #import <FlipperKit/FlipperPlugin.h>
     ~~~~~~~^
    3 errors generated.
    /Users/user_name/Documents/dev/perso/temp_app/ios/Runner/GeneratedPluginRegistrant.m:8:9: fatal error: could not build module 'flutter_flipperkit'
    #import <flutter_flipperkit/FlutterFlipperkitPlugin.h>
     ~~~~~~~^
    4 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper-DoubleConversion' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper-Glog' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'RenderCore' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper-PeerTalk' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper-Folly' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Yoga' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'ComponentKit' from project 'Pods')
    warning: no rule to process file '/Users/user_name/Documents/dev/perso/temp_app/ios/Pods/ComponentKit/ComponentKit/ComponentKit.xcconfig' of type 'text.xcconfig' for architecture 'x86_64' (in target 'ComponentKit' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper-RSocket' from project 'Pods')
    warning: no rule to process file '/Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
    warning: no rule to process file '/Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
    warning: no rule to process file '/Users/user_name/Documents/dev/perso/temp_app/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'YogaKit' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flipper' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'OpenSSL-Universal' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'CocoaLibEvent' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flutter' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'boost-for-react-native' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.


```

**Comment by paulVulog** [comment]
I finally found a working iOS pod file configuration : 

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  #use_modular_headers!
  
  # If you use `use_frameworks!` in your Podfile,
  # uncomment the below $static_framework array and also
  # the pre_install section.  This will cause Flipper and
  # it's dependencies to be built as a static library and all other pods to
  # be dynamic.
  #
  # NOTE Doing this may lead to a broken build if any of these are also
  #      transitive dependencies of other dependencies and are expected
  #      to be built as frameworks.
  #
  $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
    'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
    'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
          def pod.build_type;
            Pod::BuildType.static_library
          end
        end
      end
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by romatroskin** [comment]
> I finally found a working iOS pod file configuration :
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '9.0'
> 
> # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> project 'Runner', {
>   'Debug' => :debug,
>   'Profile' => :release,
>   'Release' => :release,
> }
> 
> def flutter_root
>   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
>   unless File.exist?(generated_xcode_build_settings_path)
>     raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
>   end
> 
>   File.foreach(generated_xcode_build_settings_path) do |line|
>     matches = line.match(/FLUTTER_ROOT\=(.*)/)
>     return matches[1].strip if matches
>   end
>   raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
> end
> 
> require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
> 
> flutter_ios_podfile_setup
> 
> target 'Runner' do
>   use_frameworks!
>   #use_modular_headers!
>   
>   # If you use `use_frameworks!` in your Podfile,
>   # uncomment the below $static_framework array and also
>   # the pre_install section.  This will cause Flipper and
>   # it's dependencies to be built as a static library and all other pods to
>   # be dynamic.
>   #
>   # NOTE Doing this may lead to a broken build if any of these are also
>   #      transitive dependencies of other dependencies and are expected
>   #      to be built as frameworks.
>   #
>   $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
>     'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
>     'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
>     'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
> 
>   pre_install do |installer|
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>     installer.pod_targets.each do |pod|
>         if $static_framework.include?(pod.name)
>           def pod.build_type;
>             Pod::BuildType.static_library
>           end
>         end
>       end
>   end
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>   end
> end
> ```

Hey, with this additions to Podfile I've got error:
ld: library not found for -lCocoaAsyncSocket

Sincerely,
Roman
